include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    missing_required_param: error
    missing_return: error
    todo: warning
    deprecated_member_use_from_same_package: warning
  exclude:
    - "**.g.dart"
    - "build/**"

linter:
  rules:
    # Enforce stricter linting
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: true
    use_build_context_synchronously: true
    unnecessary_null_checks: true
