name: Flutter CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  test:
    name: Test on ${{ matrix.os }} with Flutter ${{ matrix.flutter }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        flutter: ['3.16.0', '3.19.0', '3.22.0', 'stable']
        exclude:
          # Exclude some combinations to reduce build time
          - os: macos-latest
            flutter: '3.16.0'
          - os: windows-latest
            flutter: '3.16.0'
          - os: macos-latest
            flutter: '3.19.0'
          - os: windows-latest
            flutter: '3.19.0'

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.flutter }}
          channel: 'stable'
          
      - name: Install dependencies
        run: flutter pub get
        
      - name: Check formatting
        run: dart format --set-exit-if-changed .
        
      - name: Analyze code
        run: flutter analyze --no-fatal-infos
        
      - name: Run tests
        run: flutter test --coverage
        
      - name: Upload coverage to Codecov
        if: matrix.os == 'ubuntu-latest' && matrix.flutter == 'stable'
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/lcov.info
          name: reorderable_tree_list_view
          
      - name: Build example app
        working-directory: example
        run: |
          flutter pub get
          flutter build web --release
          
      - name: Run integration tests
        run: flutter test test/integration/
        
  build-platforms:
    name: Build on ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: web
            build-command: flutter build web --release
          - os: ubuntu-latest
            target: android
            build-command: |
              cd example
              flutter build apk --release
          - os: macos-latest
            target: ios
            build-command: |
              cd example
              flutter build ios --release --no-codesign
          - os: macos-latest
            target: macos
            build-command: |
              cd example
              flutter build macos --release
          - os: windows-latest
            target: windows
            build-command: |
              cd example
              flutter build windows --release
          - os: ubuntu-latest
            target: linux
            build-command: |
              sudo apt-get update -y
              sudo apt-get install -y ninja-build libgtk-3-dev
              cd example
              flutter build linux --release
              
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          
      - name: Install dependencies
        run: flutter pub get
        
      - name: Build ${{ matrix.target }}
        run: ${{ matrix.build-command }}
        
  publish-dry-run:
    name: Publish dry run
    runs-on: ubuntu-latest
    needs: [test, build-platforms]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          
      - name: Install dependencies
        run: flutter pub get
        
      - name: Publish dry run
        run: flutter pub publish --dry-run
        
  deploy-storybook:
    name: Deploy Storybook
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    permissions:
      contents: read
      pages: write
      id-token: write
      
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          
      - name: Build Storybook
        working-directory: example
        run: |
          flutter pub get
          flutter build web --release --base-href /${{ github.event.repository.name }}/
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'example/build/web'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4